[[transport.rabbitmq.sender]]
name = "AMQPConnectionFactory"
parameter.hostname = "armadillo.rmq.cloudamqp.com"
parameter.password = "$env{JMS_PASS}"
parameter.port = 5672
parameter.username = "iazlwjor"
