[transport.rabbitmq]
sender_enable = true

[[transport.rabbitmq.sender]]
name = "AMQPConnectionFactory"
parameter.hostname = "armadillo.rmq.cloudamqp.com"
parameter.port = 5672
parameter.username = "iazlwjor"
